- apps/backend/src/config/.env.example
- apps/backend/src/config/env-utils.ts
- apps/backend/src/interfaces/express/openapi/index.ts
- docker-compose.yml
- Set accurate swagger server urls
- To have a usable swagger on the server we need the server urls set properly
> Refactor: set accurate swagger server urls

- apps/backend/src/config/.env.example
- apps/backend/src/interfaces/sdp-embedded-wallets/index.test.ts
- apps/backend/src/interfaces/sdp-embedded-wallets/index.ts
- apps/backend/src/interfaces/sdp-embedded-wallets/mock.ts
- apps/backend/src/interfaces/sdp-embedded-wallets/types.ts
This adds the first integrations with SDP Embedded Wallets API
To be reused when creating future endpoints
> Feat: add SDP Embedded Wallets interface

- apps/web/package.json
- apps/web/src/components/molecules/ghost-button/index.tsx
- package-lock.json
Fixes: https://github.com/stellar/smart-wallet-demo-app/security/dependabot/2
> Fix(web|dependabot): form-data uses unsafe random function in form-data for choosing boundary

- apps/backend/package.json
- apps/backend/src/api/core/entities/otp/factory.test.ts
- apps/backend/src/api/core/entities/otp/factory.ts
- apps/backend/src/api/core/entities/otp/model.ts
- apps/backend/src/api/core/entities/otp/types.ts
- apps/backend/src/api/core/entities/user/model.ts
- apps/backend/src/api/core/migrations/1753275109393-create-otp-table.ts
- apps/backend/src/api/core/services/otp/index.ts
- apps/backend/src/api/core/services/otp/mocks.ts
- apps/backend/src/api/core/utils/docs/error.docs.ts
- apps/backend/src/api/core/utils/random/index.test.ts
- apps/backend/src/api/core/utils/random/index.ts
- apps/backend/src/api/embedded-wallets/docs.ts
- apps/backend/src/api/embedded-wallets/routes.ts
- apps/backend/src/api/embedded-wallets/use-cases/generate-recovery-link/index.docs.ts
- apps/backend/src/api/embedded-wallets/use-cases/generate-recovery-link/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/generate-recovery-link/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/generate-recovery-link/types.ts
- apps/backend/src/config/.env.example
- apps/backend/src/interfaces/email-provider/mock.ts
- apps/backend/src/interfaces/email-provider/sendgrid/index.ts
- apps/backend/src/interfaces/email-provider/types.ts
- docker-compose.yml
- package-lock.json
- Add email service interface (and Twilio SendGrid integration)
- Create OTP structure (entity, service, migration, general logic)
- Add POST `/send-recovery-link` endpoint
- Update docs
Used to start the recovery flow
> Feature(backend): send recovery link 

- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.test.ts
- apps/backend/src/interfaces/soroban/helpers/sc-convert.ts
Fix format for user balance return.
Need to fix formato to 7 decimals for user balance.
> fix: convert balance format

- apps/backend/src/api/core/entities/asset/factory.test.ts
- apps/backend/src/api/core/entities/asset/factory.ts
- apps/backend/src/api/core/entities/asset/model.ts
- apps/backend/src/api/core/entities/asset/types.ts
- apps/backend/src/api/core/entities/vendor/factory.test.ts
- apps/backend/src/api/core/entities/vendor/factory.ts
- apps/backend/src/api/core/entities/vendor/model.ts
- apps/backend/src/api/core/entities/vendor/types.ts
- apps/backend/src/api/core/helpers/xdr-extractor/README.md
- apps/backend/src/api/core/helpers/xdr-extractor/index.ts
- apps/backend/src/api/core/migrations/1753815882564-create-vendor-and-asset-tables.ts
- apps/backend/src/api/core/migrations/1753878721324-change-vendor-wallet-name.ts
- apps/backend/src/api/core/services/asset/index.ts
- apps/backend/src/api/core/services/asset/mock.ts
- apps/backend/src/api/core/services/vendor/index.ts
- apps/backend/src/api/core/services/vendor/mock.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/types.ts
- apps/backend/src/interfaces/wallet-backend/types.ts
Add vendor and assets tables.
To get vendor and asset data to return with tx history feat.
> Feature (backend): vendors and assets crud

- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/types.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet/index.ts
- apps/backend/src/interfaces/soroban/helpers/sc-convert.ts
Change format of the returned amounts.
Change returned amount format to unsigned number.
> fix: change amount formats to unsigned number

- apps/web/src/interfaces/qr-scanner/index.ts
- Fixes the qr-scanner to stop logging not trackable errors
- If we don't stop logging it, it will dispatch these errors on every frame change
> Fix(web): filter not trackable errors on qr-scanner

- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/types.ts
- apps/web/package.json
- apps/web/src/app/core/utils/format-stellar-address/index.ts
- apps/web/src/app/core/utils/index.ts
- apps/web/src/app/wallet/pages/profile/template.tsx
- apps/web/src/app/wallet/pages/transactions/template.tsx
- apps/web/src/helpers/format/index.ts
- package-lock.json
- (web) redact contract addresses if they appear on tx history
- Ensure the UI will not break even for a long tx amount
- UI was breaking on tx history
> Fix(web): broken layout on tx history

- apps/backend/src/api/core/helpers/get-balance/index.ts
- apps/backend/src/api/embedded-wallets/constants/messages.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/types.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer/index.ts
- apps/backend/src/interfaces/soroban/helpers/sc-convert.ts
Feature to transfer NFTs to a given address
Add option to transfer NFT on `GET /transfer/options` and `POST /transfer/complete`
> feat: NFT transfer

- apps/web/src/app/auth/constants/storage.ts
- apps/web/src/app/core/helpers/feature-flags-state/index.ts
- apps/web/src/app/core/helpers/index.ts
- apps/web/src/app/core/queries/query-keys.ts
- apps/web/src/app/core/queries/use-get-feature-flags.ts
- apps/web/src/app/core/router/routeTree.ts
- apps/web/src/app/core/services/setttings/index.ts
- apps/web/src/app/core/services/setttings/types.ts
- apps/web/src/app/wallet/pages/home/index.tsx
- apps/web/src/app/wallet/pages/home/template.tsx
- apps/web/src/app/wallet/store/airdrop/airdrop.store.test.ts
- apps/web/src/app/wallet/store/airdrop/index.ts
- apps/web/src/app/wallet/store/airdrop/types.ts
- apps/web/src/app/wallet/store/index.ts
- Adds feature flags service (settings service)
- Adds query and helper
- Applies feature flag to `coming-soon` and `airdrop` use cases
- Mandatory tool toggle functionalities on the web app
> Feature(web): create web feature flags structure

- apps/backend/src/api/core/entities/product/factory.test.ts
- apps/backend/src/api/core/entities/product/factory.ts
- apps/backend/src/api/core/entities/product/model.ts
- apps/backend/src/api/core/entities/product/types.ts
- apps/backend/src/api/core/migrations/1755181277093-add-product.ts
- apps/backend/src/api/core/services/product/index.ts
- apps/backend/src/api/core/services/product/mocks.ts
- apps/backend/src/api/embedded-wallets/use-cases/gift-complete/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/gift-options/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer-options/types.ts
- apps/web/src/app/wallet/hooks/use-init-transfer.ts
- apps/web/src/app/wallet/pages/home/schema.ts
- apps/web/src/app/wallet/services/wallet/types.ts
- apps/web/src/components/organisms/modal/variants/transaction-details.tsx
- [Backend] Create product model and migration
- [Backend] Return product information on `transfer-options` endpoint
- [Web] Render product description on transaction-details modal
- Enable visualization of product description while performing a transfer
> Feature: add product to transfer flow

- apps/web/src/app/auth/pages/invite/index.tsx
- apps/web/src/app/auth/pages/login/index.tsx
- apps/web/src/app/auth/pages/login/template.tsx
- apps/web/src/app/auth/pages/recover-confirm/index.tsx
- apps/web/src/app/auth/store/access-token/index.ts
- apps/web/src/app/core/router/components/index.ts
- apps/web/src/app/core/router/components/loading/index.tsx
- apps/web/src/app/core/router/index.ts
- apps/web/src/app/wallet/hooks/use-init-transfer.ts
- apps/web/src/app/wallet/hooks/use-nfts.ts
- apps/web/src/app/wallet/pages/home/index.tsx
- apps/web/src/app/wallet/pages/home/template.tsx
- apps/web/src/app/wallet/pages/profile/index.tsx
- apps/web/src/app/wallet/pages/transactions/index.tsx
- apps/web/src/app/wallet/routes/index.tsx
- apps/web/src/config/content.example.json
- apps/web/src/helpers/error-handling/index.ts
- apps/web/src/interfaces/query-client/index.ts
- apps/web/src/query-client.d.ts
- (React-query)
- Add `forceRefresh` custom method
- Add `clearExcept` custom method
- Modify queries usage on the app to check loading status from `isLoading` instead of `isPending`
- For flows where users become authenticated, now we have a `isRedirecting` state that will lock the page on its current loading state until the navigation completes
- Enhance user UX on the app
> Fix(web): ux polishes

- apps/backend/src/api/core/entities/user/factory.ts
- apps/backend/src/api/core/entities/user/types.ts
- apps/backend/src/api/core/helpers/get-balance/index.ts
- apps/backend/src/api/core/services/user/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/get-wallet/types.ts
Return user tokens balances on get-wallet endpoint
To display and control user tokens balances
> feat: return user tokens balances on get-wallet

- apps/backend/src/api/core/entities/vendor/types.ts
- apps/backend/src/api/core/routes.ts
- apps/backend/src/api/core/services/vendor/index.ts
- apps/backend/src/api/core/services/vendor/mock.ts
- apps/backend/src/api/core/utils/zod/index.ts
- apps/backend/src/api/general-settings/docs.ts
- apps/backend/src/api/general-settings/routes.ts
- apps/backend/src/api/general-settings/use-cases/create-vendor/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/create-vendor/index.test.ts
- apps/backend/src/api/general-settings/use-cases/create-vendor/index.ts
- apps/backend/src/api/general-settings/use-cases/create-vendor/types.ts
- apps/backend/src/api/general-settings/use-cases/get-vendors/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/get-vendors/index.test.ts
- apps/backend/src/api/general-settings/use-cases/get-vendors/index.ts
- apps/backend/src/api/general-settings/use-cases/get-vendors/types.ts
- apps/backend/src/api/general-settings/use-cases/update-vendor/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/update-vendor/index.test.ts
- apps/backend/src/api/general-settings/use-cases/update-vendor/index.ts
- apps/backend/src/api/general-settings/use-cases/update-vendor/types.ts
- Create new endpoints:
- GET `api/admin/vendors`
- POST `api/admin/vendors`
- PATCH `api/admin/vendors/:id`
- Update docs and tests
To allow vendors creation and edition
> Feature(backend): create vendors endpoints

- apps/backend/src/api/core/entities/nft-supply/factory.ts
- apps/backend/src/api/core/entities/nft-supply/types.ts
- apps/backend/src/api/core/routes.ts
- apps/backend/src/api/core/services/nft-supply/index.ts
- apps/backend/src/api/core/services/nft-supply/mock.ts
- apps/backend/src/api/core/utils/zod/index.ts
- apps/backend/src/api/general-settings/routes.ts
- apps/backend/src/api/general-settings/use-cases/create-nft-supply/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/create-nft-supply/index.test.ts
- apps/backend/src/api/general-settings/use-cases/create-nft-supply/index.ts
- apps/backend/src/api/general-settings/use-cases/create-nft-supply/types.ts
- apps/backend/src/api/general-settings/use-cases/get-nft-supply/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/get-nft-supply/index.test.ts
- apps/backend/src/api/general-settings/use-cases/get-nft-supply/index.ts
- apps/backend/src/api/general-settings/use-cases/get-nft-supply/types.ts
- apps/backend/src/api/general-settings/use-cases/update-nft-supply/index.docs.ts
- apps/backend/src/api/general-settings/use-cases/update-nft-supply/index.test.ts
- apps/backend/src/api/general-settings/use-cases/update-nft-supply/index.ts
- apps/backend/src/api/general-settings/use-cases/update-nft-supply/types.ts
Add endpoints to NFT collection CRUD
Endpoints to create, update and delete NFT collections
> feat (backend): NFT collection CRUD

- apps/web/src/app/core/router/components/layout/index.tsx
> Hotfix(web): desktop scroll locked

- apps/backend/src/api/core/entities/nft/model.ts
- apps/backend/src/api/core/entities/nft/types.ts
- apps/backend/src/api/core/framework/orm/base.ts
- apps/backend/src/api/core/migrations/1756839553084-add-nft-soft-delete.ts
- apps/backend/src/api/core/services/nft/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/claim-nft-options/index.test.ts
- apps/backend/src/api/embedded-wallets/use-cases/claim-nft-options/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/claim-nft/index.ts
- apps/backend/src/api/embedded-wallets/use-cases/transfer/index.ts
- Add soft delete strategy for NFTs
- To keep track of all NFTs claimed
> Feat(backend): soft delete nfts

- apps/web/src/app/auth/pages/invite/template.tsx
> fix(web): wrong invite page check

- apps/web/README.md
- apps/web/src/app/wallet/pages/home/index.tsx
- apps/web/src/config/.env.example
> fix(web): faq not rendering on CI

- apps/backend/src/api/core/entities/passkey/types.ts
- apps/backend/src/api/core/helpers/webauthn/registration/index.ts
- apps/backend/src/api/core/services/passkey/index.ts
- apps/backend/src/api/core/services/passkey/mocks.ts
- apps/backend/src/api/core/utils/file/index.ts
- apps/web/src/app/auth/constants/storage.ts
- apps/web/src/app/auth/pages/invite-resend/template.tsx
- apps/web/src/app/auth/pages/invite/index.tsx
- apps/web/src/app/auth/pages/login/index.tsx
- apps/web/src/app/auth/pages/login/template.tsx
- apps/web/src/app/auth/pages/recover-confirm/index.tsx
- apps/web/src/app/auth/pages/recover/template.tsx
- apps/web/src/app/auth/routes/index.tsx
- apps/web/src/app/core/helpers/feature-flags-state/index.ts
- apps/web/src/app/core/store/deep-link/deep-link.store.test.ts
- apps/web/src/app/core/store/deep-link/index.ts
- apps/web/src/app/core/store/deep-link/types.ts
- apps/web/src/app/core/store/index.ts
- apps/web/src/app/wallet/hooks/use-deep-link.ts
- apps/web/src/app/wallet/hooks/use-feature-flags-refetch-on-focus.ts
- apps/web/src/app/wallet/hooks/use-handle-behind-scenes.ts
- apps/web/src/app/wallet/pages/home/index.tsx
- apps/web/src/app/wallet/pages/left-assets/tabs/transfer-assets/template.tsx
- Delete previous passkeys on recovery flow
- Deep link
- Refetch feature flags on wallet home page
- Enhance UX and fix non-expected behaviors
> Hotfix: general issues

- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.ts
> Hotfix(backend): missing airdrop tx in history

- apps/backend/src/api/core/helpers/webauthn/registration/index.ts
> fix(backend): check passkey length before deletion

- apps/backend/src/interfaces/email-provider/sendgrid/index.ts
> fix: remove sendgrid link tracker

- apps/backend/src/api/core/routes.ts
- apps/backend/src/api/general-settings/routes.ts
- apps/backend/src/api/general-settings/use-cases/resolve-redirect-url/index.ts
- apps/backend/src/api/general-settings/use-cases/resolve-redirect-url/types.ts
- apps/web/src/app/wallet/domain/use-cases/scan-qr-code/index.ts
- apps/web/src/app/wallet/pages/scan/template.tsx
> feat: add follow link redirect for minified qr codes

- apps/web/src/components/organisms/layout/index.tsx
> fix: height issue for safary

- apps/web/src/app/wallet/services/wallet/index.ts
> Hotfix(web): remove G from session_id

- apps/backend/src/api/embedded-wallets/use-cases/get-wallet-history/index.ts
Fix history to show correct amount on multi-swag transfer
> fix: multi swag tranfer operation on tx history

- apps/backend/src/api/core/helpers/webauthn/authentication/index.ts
- apps/backend/src/api/core/helpers/webauthn/authentication/webauthn-authentication.test.ts
- apps/backend/src/api/core/helpers/webauthn/registration/index.ts
- apps/backend/src/api/core/helpers/webauthn/registration/webauthn-registration.test.ts
- Increases webauthn auth/registration timeout
- Enhance UX while using bad wifi
> Feat: increase webauthn timeout
