.github/workflows/backend.set-outputs.yaml
.github/workflows/web.set-outputs.yaml

- Set outputs for workflow_call on set-outputs workflow
- Missing outputs for workflow_call on set-outputs workflow

Fix: missing outputs for workflow_call on set-outputs workflow

---

.github/workflows/backend.deploy-heroku.yaml
.github/workflows/backend.deploy.yaml
.github/workflows/web.deploy-heroku.yaml
.github/workflows/web.deploy.yaml

- Put fixed heroku release params
- Wrong heroku release params (POST command on workflow)

Fix: wrong heroku release params

---

.github/workflows/backend.deploy-heroku.yaml
.github/workflows/web.deploy-heroku.yaml
.github/workflows/web.deploy.yaml

- Stop passing unnecessary/wrong params to deploy-heroku workflows
- Causing errors during the action's runtime

Fix: wrong params to deploy to heroku

---

.github/workflows/backend.deploy-heroku.yaml
.github/workflows/web.deploy-heroku.yaml

- Use heroku cli to release builds on CI
- Keep the CI accurate with the Heroku CLI changes, instead of directly calling the API

Refactor: use heroku cli to release builds on CI

---

apps/web/src/app/auth/pages/invite/index.tsx
apps/web/src/app/auth/routes/components/auth-route-loading/index.tsx
apps/web/src/app/auth/routes/index.tsx

- Fixes: search param usage breaking invite page
- `useSearch` loses reference to the inviteRoute
- Uses `useSearch` directly from the `inviteRoute` instance

Fix(web): search param usage breaking invite page

---

apps/backend/src/api/embedded-wallets/docs.ts

Add tx history docs
Enable transaction history docs on Swagger

docs: add tx history docs

---

apps/backend/src/api/embedded-wallets/constants/messages.ts
apps/backend/src/api/embedded-wallets/use-cases/get-wallet/index.test.ts
apps/backend/src/api/embedded-wallets/use-cases/get-wallet/index.ts
apps/backend/src/api/embedded-wallets/use-cases/get-wallet/types.ts
apps/web/src/app/wallet/pages/home/index.tsx
apps/web/src/app/wallet/services/wallet/types.ts

- Returns wallet balance as a number (human readable, losing precision ⚠️ )
- (web) renders wallet balance on the wallet home page
- Always return wallet info on `GET get-wallet`
- If for some reason the contract address are not available, it will throw an exception
- Reduces web friction for new users
- Leave the web locale format the asset

Refactor: always send wallet info on get wallet

---

apps/backend/src/interfaces/soroban/helpers/sc-convert.ts
apps/web/src/app/wallet/pages/transactions/template.tsx
apps/web/src/components/molecules/asset-amount/index.tsx
apps/web/src/components/organisms/modal/variants/transaction-details.tsx

- Correctly parse amount before building tx
- It was not properly formatting the transfer amount

Refactor: parseFloat amount before transform to scVal

---

apps/web/src/app/auth/constants/storage.ts
apps/web/src/app/wallet/domain/models/transaction.ts
apps/web/src/app/wallet/domain/use-cases/get-wallet/index.ts
apps/web/src/app/wallet/domain/use-cases/get-wallet/types.ts
apps/web/src/app/wallet/hooks/use-init-transfer.ts
apps/web/src/app/wallet/pages/home/index.tsx
apps/web/src/app/wallet/pages/profile/index.tsx
apps/web/src/app/wallet/pages/transactions/index.tsx
apps/web/src/app/wallet/pages/transactions/template.tsx
apps/web/src/app/wallet/queries/use-get-wallet.ts
apps/web/src/app/wallet/store/index.ts
apps/web/src/app/wallet/store/wallet-address/index.ts
apps/web/src/app/wallet/store/wallet-address/types.ts
apps/web/src/app/wallet/store/wallet-address/wallet-address.store.test.ts
apps/web/src/app/wallet/utils/index.ts
apps/web/src/app/wallet/utils/map-tx-vendor-name/index.ts
apps/web/src/components/organisms/modal/variants/transaction-details.tsx

- Refactors the transaction history order (and add send/receive rule)
- Bonus: move get wallet to use case (in order to store wallet address on local storage)
- Leave the most recents tx at the top and properly render vendor name (or address)

Refactor(web): transaction history order and send receive rule

---

apps/backend/src/api/core/framework/retryable/interface.ts
apps/backend/src/api/core/framework/retryable/retryable.test.ts
apps/backend/src/interfaces/soroban/index.ts

- Increases RPC server timeout
- Creates `retryable` interface
- Abstract class that has a generic `retry` method. Useful to wrap any kind of promise that may require retries
- Update `soroban` interface to use `retryable` on every `rpc` call
- Improves the API to automatically handle blockchain delays

Feat(backend): create retryable interface and apply it on soroban interface

---

apps/web/src/app/core/error-boundary/index.tsx
apps/web/src/instrument.ts
apps/web/src/interfaces/http/interceptors.ts

This catches Sentry errors so that they are not visible to the user.
Sentry requests can fail for users with ad blockers installed.

Fix(web): Catch Sentry errors

---

apps/web/src/app/wallet/pages/special-gift/template.tsx

- Fixes the `special-gift` template to stop overlapping text when images have vertical proportion
- It should not overlap components for any kind of image

Fix(web): special gift template overlapping text

---

apps/web/src/app/wallet/domain/use-cases/get-wallet/types.ts
apps/web/src/app/wallet/pages/home/index.tsx
apps/web/src/app/wallet/services/wallet/types.ts

- Disables `left-assets` banner once the user has empty assets
- `left-assets` flow only makes sense if the user still has pending assets

Feat(web): disable left-assets banner once empty assets

---

apps/backend/src/api/core/entities/user/model.ts
apps/backend/src/api/core/migrations/1756300000000-create-created-account-table.ts
apps/backend/src/api/embedded-wallets/constants/messages.ts
apps/backend/src/api/embedded-wallets/routes.ts
apps/backend/src/api/embedded-wallets/use-cases/create-account/index.docs.ts
apps/backend/src/api/embedded-wallets/use-cases/create-account/index.test.ts
apps/backend/src/api/embedded-wallets/use-cases/create-account/index.ts
apps/backend/src/api/embedded-wallets/use-cases/create-account/types.ts
apps/backend/src/api/embedded-wallets/use-cases/create-wallet/index.test.ts
apps/backend/src/interfaces/wallet-backend/index.ts
apps/backend/src/interfaces/wallet-backend/mock.ts
apps/backend/src/interfaces/wallet-backend/types.ts

This implements the `/create-account` endpoint, which creates a Stellar account if it doesn't already exist. This endpoint is allowed to be called once per user.
Sponsor accounts that don't already exist for end of event transfer.

Feature(backend): Implement account creation API

---

apps/backend/src/api/core/entities/nft-supply/model.ts
apps/backend/src/api/core/entities/nft-supply/types.ts
apps/backend/src/api/core/routes.ts
apps/backend/src/api/core/services/nft-supply/index.ts
apps/backend/src/api/core/services/nft-supply/mock.ts
apps/backend/src/api/core/utils/zod/index.ts
apps/backend/src/api/general-settings/routes.ts
apps/backend/src/api/general-settings/use-cases/get-nft-metadata/index.ts
apps/backend/src/api/general-settings/use-cases/get-nft-metadata/types.ts

Endpoint that returns NFT metadata in SEP-50 format
`GET http://localhost:8000/nft-metadata/:resource/token_id`
`GET http://localhost:8000/nft-metadata/talk/18`
So that external integrations can get token metadata to render properly.

feat: endpoint to return nft metadata

---

apps/web/src/interfaces/qr-scanner/index.ts

What
Added pinch-to-zoom functionality to the QR scanner component, allowing users to control camera zoom levels using two-finger pinch gestures on touch devices.
Why
The existing QR scanner lacked intuitive zoom controls for users to better focus on QR codes at different distances. This enhancement improves the user experience by providing native camera-like zoom functionality that users expect from modern mobile applications. The implementation uses touch events to detect pinch gestures and maps them to camera zoom levels, making QR code scanning more accessible and user-friendly across different device types and scanning scenarios.
Checklist
PR Structure
[x] It is not possible to break this PR down into smaller PRs.
[x] This PR does not mix refactoring changes with feature changes. …

feat: add zoom capabilities to qr code scanner

---

scripts/helpers/pinata.mjs

update nft scripts to allow other types besides png
because mainly png, svg and mp4 will be used but other types are also supported
logs:
```
cd scripts && npm run deploy-nft-ipfs -- \
--source-account admin \
--name "My Awesome Collection" \
--symbol "MAC" \
--supply 2 \
--network testnet
> scripts@1.0.0 deploy-nft-ipfs
> node nft/deploy-nft-ipfs.mjs --source-account admin --name My Awesome Collection --symbol MAC --supply 2 --network testnet
Target Network: testnet
Source Account: admin
Contract Name: My Awesome Collection
Contract Symbol: MAC
Max Supply: 2
installing pinata cli
checking if pinata cli is installed...
✓ pinata cli is already installed
pinata authentication
setting up pinata cli authentication...
✓ pinata cli is already authenticated
Running: make build
stellar contract …
```

fix(nft): update nft scripts to allow other types besides png

---

contracts/nft/src/contract.rs
contracts/nft/src/test.rs
scripts/helpers/pinata.mjs

make set_token_data private because it has no auth check and it is used only in mint_with_data (which does the auth check)
so unauthorized actors can't invoke set_token_data

refactor(nft): make set_token_data private

---

apps/backend/src/api/embedded-wallets/use-cases/list-nft/index.test.ts
apps/backend/src/api/embedded-wallets/use-cases/list-nft/index.ts

Remove call to getTokenData from NFT list when parsing data
It was causing slow response and that data was no longer needed.

fix: remove getTokenData call from nft list

---

apps/web/src/app/wallet/pages/left-assets/tabs/transfer-nfts/index.tsx
apps/web/src/config/content.example.json

- Adds limit to left-nfts transfer
- API limitation for bulk_transfer nfts (we got errors on the chain level)
| | |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/59485d03-5b52-40f3-bc76-1c95ac38a6dd" />  | <video src="https://github.com/user-attachments/assets/e059a8a9-f095-4bdb-b7f2-8fa17867b4c0" /> |

Feat(web): add limit to left-nfts transfer
